from __future__ import annotations

import json
from pathlib import Path

from arango_query_core import MappingBundle, MappingSource


def mapping_bundle_for(name: str) -> MappingBundle:
    """
    Load mapping fixtures generated by `arangodb-schema-analyzer` (tool contract `export`).
    """
    n = name.strip().lower()
    root = Path(__file__).resolve().parents[2]
    p = root / "tests" / "fixtures" / "mappings" / f"{n}.export.json"
    if not p.exists():
        raise FileNotFoundError(f"Missing mapping fixture: {p}")

    raw = json.loads(p.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"Invalid mapping fixture JSON: {p}")

    conceptual = raw.get("conceptualSchema")
    physical = raw.get("physicalMapping")
    metadata = raw.get("metadata")
    if not isinstance(conceptual, dict) or not isinstance(physical, dict) or not isinstance(metadata, dict):
        raise ValueError(f"Invalid mapping fixture shape: {p}")

    return MappingBundle(
        conceptual_schema=conceptual,
        physical_mapping=physical,
        metadata=metadata,
        source=MappingSource(kind="schema_analyzer_export", notes=f"loaded from {p.name}"),
    )

